import Link from "next/link";
import React from "react";
import styles from "./styles.module.css";

const Profile = () => {
  return (
    <>
      <h1>Profile</h1>
      <div className={styles.productsGrid}>
        <Link href="/">Volver</Link>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
        <div className={styles.product}></div>
      </div>
    </>
  );
};

export default Profile;
